name: python_social_media_backend
on:
  push:
    branches:
      - "dev_fastapi"
  pull_request:
    branches:
      - "dev_fastapi"
jobs:
  fastapi_job:
    runs-on: windows-latest
    steps:
      - name: Hello User
        run: Hello, ${{github.actor}} 
      - name: pulling git repo
        uses: actions/checkout@v4
      - name: install python version 3.10.0
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.0'
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: installing dependencies
        run: pip install -r requirements.txt