name: python_social_media_backend
on:
  push:
    branches:
      - "dev_fastapi"
  pull_request:
    branches:
      - "dev_fastapi"
jobs:
  fastapi_job:
    runs-on: windows-latest
    environment:
      name: testing
    steps:
      - name: Hello User
        run: echo Hello ${{ github.actor }} 

      - name: Pulling Git Repository
        uses: actions/checkout@v4

      - name: Set Up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.0'

      - name: Upgrade Pip
        run: python -m pip install --upgrade pip

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Pytest with Coverage
        env:
          DATABASE_HOSTNAME: ${{ secrets.DATABASE_HOSTNAME }}
          DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          TEST_DATABASE_NAME: ${{ secrets.TEST_DATABASE_NAME }}
          DATABASE_NAME1: ${{ secrets.DATABASE_NAME1 }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ALGORITHM: ${{ secrets.ALGORITHM }}
          ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
          DATABASE_STRING: ${{ secrets.DATABASE_STRING }}
        run: |
          pip install pytest
          pip install pytest-cov
          pytest
          pytest --cov=app